using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wallet.App.BillDetails
{
    public class BillDetailManager : BillDetailManagerBase
    {
        //<suite-custom-code-autogenerated>
        public BillDetailManager(IBillDetailRepository billDetailRepository)
            : base(billDetailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}