using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Wallet.App.PaymentTypeCategories
{
    public class PaymentTypeCategoryManager : PaymentTypeCategoryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PaymentTypeCategoryManager(IPaymentTypeCategoryRepository paymentTypeCategoryRepository)
            : base(paymentTypeCategoryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}